/**
 * TEMP — fetch a real post and convert its TipTap JSON to email HTML with a
 * small self-contained walker (no `novel` import — that breaks standalone Node,
 * and per the project's "TipTap preview walker" rule we hand-roll instead).
 *
 * The real send uses @tiptap/html generateHTML; for the node/mark set Carlos
 * actually uses (paragraph, heading, blockquote, text + bold/italic/link) the
 * output is equivalent. Like the real path, this does NOT run normalizeEmojiLists,
 * so emoji-led lines stay as <p> — exactly what ships today.
 *
 *   node _tmp_fetch_post.ts 175
 * Delete after use (the generated fixture too).
 */
import { readFileSync, writeFileSync } from "node:fs";

function loadEnv(path: string): Record<string, string> {
	const out: Record<string, string> = {};
	for (const line of readFileSync(path, "utf8").split("\n")) {
		const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
		if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, "").trim();
	}
	return out;
}

const esc = (s: string) =>
	s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const escAttr = (s: string) => esc(s).replace(/"/g, "&quot;");

function renderText(node: any): string {
	let html = esc(node.text ?? "");
	for (const mark of node.marks ?? []) {
		if (mark.type === "bold") html = `<strong>${html}</strong>`;
		else if (mark.type === "italic") html = `<em>${html}</em>`;
		else if (mark.type === "underline") html = `<u>${html}</u>`;
		else if (mark.type === "code") html = `<code>${html}</code>`;
		else if (mark.type === "link") {
			const href = escAttr(mark.attrs?.href ?? "#");
			const target = mark.attrs?.target ? ` target="${escAttr(mark.attrs.target)}"` : "";
			const rel = mark.attrs?.rel ? ` rel="${escAttr(mark.attrs.rel)}"` : "";
			html = `<a href="${href}"${target}${rel}>${html}</a>`;
		}
	}
	return html;
}

function renderChildren(node: any): string {
	return (node.content ?? []).map(render).join("");
}

function render(node: any): string {
	switch (node.type) {
		case "doc":
			return renderChildren(node);
		case "paragraph":
			return `<p>${renderChildren(node)}</p>`;
		case "heading":
			return `<h${node.attrs?.level ?? 2}>${renderChildren(node)}</h${node.attrs?.level ?? 2}>`;
		case "blockquote":
			return `<blockquote>${renderChildren(node)}</blockquote>`;
		case "bulletList":
			return `<ul>${renderChildren(node)}</ul>`;
		case "orderedList":
			return `<ol>${renderChildren(node)}</ol>`;
		case "listItem":
			return `<li>${renderChildren(node)}</li>`;
		case "text":
			return renderText(node);
		case "hardBreak":
			return "<br/>";
		case "horizontalRule":
			return "<hr/>";
		default:
			return renderChildren(node);
	}
}

async function main() {
	const id = process.argv[2] ?? "175";
	const env = loadEnv(".env.local");
	const url = env.NEXT_PUBLIC_SUPABASE_URL;
	const key = env.SUPABASE_SERVICE_ROLE_KEY;
	const res = await fetch(
		`${url}/rest/v1/posts?id=eq.${id}&select=id,title,content,slug,authors(name,image_url)`,
		{ headers: { apikey: key, Authorization: `Bearer ${key}` } },
	);
	const rows = await res.json();
	if (!Array.isArray(rows) || rows.length === 0) {
		throw new Error(`Post ${id} not found: ${JSON.stringify(rows).slice(0, 300)}`);
	}
	const post = rows[0];
	const html = render(post.content);
	const author = post.authors?.[0]?.name ?? post.authors?.name ?? "Carlos Resende";
	const slug = post.slug;
	const rawImg = post.authors?.[0]?.image_url ?? post.authors?.image_url ?? null;
	const authorImageUrl = rawImg
		? rawImg.startsWith("http")
			? rawImg
			: `https://adamastor.blog${rawImg}`
		: undefined;
	const fixture = `// TEMP preview fixture — real content from post ${id} ("${post.title.replace(/"/g, "'")}").
// Generated by _tmp_fetch_post.ts. Plain string export → the email server never imports novel.
// Safe to delete once you've reviewed the real-content preview.
export const post${id} = {
	id: ${JSON.stringify(String(post.id))},
	title: ${JSON.stringify(post.title)},
	authorName: ${JSON.stringify(author)},
	authorImageUrl: ${JSON.stringify(authorImageUrl)},
	url: ${JSON.stringify(slug ? `https://adamastor.blog/posts/${slug}` : `https://adamastor.blog/posts/${post.id}`)},
	htmlContent: ${JSON.stringify(html)},
};
`;
	writeFileSync(`components/email/_fixtures/post-${id}.ts`, fixture);
	console.log(`title:  ${post.title}`);
	console.log(`author: ${author}`);
	console.log(`html:   ${html.length} chars`);
	console.log(`wrote:  components/email/_fixtures/post-${id}.ts`);
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
